### ISSUE TITLE
屋台IDの取得方法についての検討

### ISSUE THREAD

**Issue by tsc-htakahashi** [shimada-shimasho/shimadataisai-gae#8]
- 屋台IDをどのように取得するか？

1. 屋台クライアントで初回に指定する（誤操作で変更されてしまわないか？）
1. GAEアプリを屋台ごとに別バージョンをデプロイし、屋台とバージョンを関係付ける（node.jsから稼働中バージョンを取得できるか？）

- 屋台IDに対応する屋台名の取得はどうするか？

1. コード中にハードコーディングする
1. Firestoreに事前に登録しておく（キャッシュする？）

**Comment by tsc-htakahashi** [comment]
- process.env.GAE_VERSION(環境変数 GAE_VERSION)でインスタンスのデプロイバージョンを取得可能なので、バージョンIDを屋台と関連付ければ、サーバー側プログラム内で屋台を判別可能
- 屋台1用をバージョン1、屋台2用をバージョン2、、、とし、屋台1からは 1-dot-shimada-taisai.appspot.comへアクセスする
- 観光客用バージョンのみにトラフィックを割り当てれば、shimada-taisai.appspot.comへアクセスした際は、観光客用バージョンに振り分けられ屋台用バージョンには振り分けられない

**Comment by Hiro11190422** [comment]
- 屋台IDについて
　３日間のみの運用なので、屋台ごとに初回設定をお願いするようにしていけば良いと考えていました。具体的な方法としては、選択ミスを防ぐため、スマホ端末のスリープモードを解除し、常に選択している屋台名を大きく表示することで、ミスを防げるのではないでしょうか？
（もし、データが上がってこない屋台があった場合、当日生徒が走って状況を確認します）

- 屋台IDと屋台名について
　観光客用のバージョンに、ハードコーディングする形がコード量は増えても、作成ステップ数が減らせると思うので、ハードコーディングで進めていき
　今後の展開につなげるためにも、最終的にはdetastoreに保存し取得する形にしていくようにしたいです。

**Comment by tsc-htakahashi** [comment]
先のコメント(9/8 15:20)に書きましたが、サーバー側プログラムで稼働しているバージョンを取得可能でした。
次のように屋台ごとにアクセスURLを決めておけば、屋台IDの選択が不要となるので、ミスも防げそうです。
屋台IDと屋台名については、開発期間が短いこともありますし、ハードコーディングで良いと思います。
- 屋台1: 1-dot-shimada-taisai.appspot.com
- 屋台2: 2-dot-shimada-taisai.appspot.com
- 屋台3: 3-dot-shimada-taisai.appspot.com
- …
- 観光客: shimada-taisai.appspot.com
----
Google App Engine特有の仕組みの部分なので、イメージしにくいかもしれません。
必要ならもう少し詳しい説明をWikiに記載します。
